# Aiven MySQL Configuration

spring.datasource.url=jdbc:mysql://mysql-1bc3da6d-arjunp1152-b0c7.g.aivencloud.com:12714/defaultdb?sslMode=REQUIRED

spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false

server.port=8080


